### ISSUE TITLE
[SC] StartService ERROR 1168:  Element not found.

### ISSUE THREAD

**Issue by FaBeyyy** [Mattiwatti/PPLKiller#2] opened 2017-08-12 03:04 UTC
I did everything listed here but it tells me the service was not found when trying **sc start pplkiller or net sc start**.
The weird thing is, that eg. **sc GetKeyName** or other calls are working, i didnt change the name of the service or anything.
Trying to start the service with ProcessHacker gives me the same error.

**Comment by Mattiwatti** [comment] 2017-08-12 10:25
This is probably caused by PPLKiller failing to find the correct `EPROCESS` offsets rather than `sc` not working. You can check this by going to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter` in regedit (create the key if it doesn't exist) and adding a `DWORD` named `IHVDRIVER` with a value of `0xf` (reboot required). You can then see PPLKiller printing info in [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview).

I've noticed finding the signature level offset has become inaccurate recently (at least in Windows 10 RS2). I'm planning on rewriting this, but meanwhile you can hardcode the offsets to `0x6C8` and `0x6C9` respectively for the signature level and section signature level offset respectively, as those are currently the only correct values. Finding the offsets also seems to have a better chance of success right after boot. I'll look into which process(es) are involved in messing up this check.

**Comment by Mattiwatti** [comment] 2017-10-03 05:18
I believe this should be fixed now with the latest commit, can you confirm?

The offset search is now working reliably for me on both RS2 and the RS3 preview (10.0.16299.0).

**Comment by Mattiwatti** [comment] 2017-10-03 05:43
Aargh, scratch that. I tried it without a kernel debugger attached and it failed once more. I should have expected as much, Patchguard does the same thing after all. Looks like I'm either going to have to BSOD-test-repeat this until it works or patch a whole lot of 'cmp KdDebuggerEnabled, 0' checks out of the kernel. Bah.

**Comment by Mattiwatti** [comment] 2017-10-03 10:13
OK, I believe 7a798af will have finally fixed this. The issue was simply that some processes other than System are also set to 'TCB' signing level (the highest)... when there is no kernel debugger attached. The check has been relaxed so that usermode processes can also have a TCB signing level and be robbed of it when the driver runs.

**Comment by Mattiwatti** [comment] 2017-11-06 16:29
Closing this as I haven't encountered or heard of any problems finding the offsets after those two commits. The driver should now work on both RS2 and RS3. Please re-open if this is not the case.

**Closed by Mattiwatti** 2017-11-06 16:29 UTC
