### ISSUE TITLE
error  : Unable to read the project file "PPLKiller.vcxproj

### ISSUE THREAD

**Issue by roboserg** [Mattiwatti/PPLKiller#3] opened 2017-11-06 14:27 UTC
Win10 64, Visual Studio 2017, latest WDK. Cant open the solution

C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.KernelMode.Default.props(15,11): A numeric comparison was attempted on "$(_NT_TARGET_VERSION)" that evaluates to "" instead of a number, in condition "$(_NT_TARGET_VERSION) >= $(_NT_TARGET_VERSION_WIN10)".

**Comment by Mattiwatti** [comment] 2017-11-06 14:39
Do you have any old WDK versions installed? This is a bug that was only fixed in the latest WDK (10.0.16299.0) and present in all Windows 10 WDKs before it. Someone I know only managed to get the latest WDK to work by first uninstalling the WDK and all SDK versions, then reinstalling (only) SDK 10.0.16299.0, and then (only) WDK 10.0.16299.0. Though I don't know if they were getting the same error as this or another one.

**Comment by roboserg** [comment] 2017-11-06 14:46
The only WDK I have is the one I installed right now 10.0.14393.0 It seems not the latest one? Weird, as it should have automatically got me the latest.

**Comment by Mattiwatti** [comment] 2017-11-06 14:52
Yep. You're two versions behind ;)
I've updated the download link in the README, it now points to the one for Windows 10 1709.

**Comment by roboserg** [comment] 2017-11-06 15:13
Installing the latest WDK 1709 solved the problem. Didnt have to reinstall the SDKs, thank you!

But now I get the following error when starting the pplkiller - [https://puu.sh/yg5O2/4e41db3233.png](url)

CMD is ran as admin

**Comment by roboserg** [comment] 2017-11-06 15:20
Restarting PC solved the issue. I managed to strip the protection, but after turning PPLkiller off with the process still has no protection. Tested on csrss.exe

**Comment by Mattiwatti** [comment] 2017-11-06 15:32
It's unlikely that's the case, because **stopping** PPLKiller does literally nothing other than make the system unload the driver. PPLKiller isn't maintaining some magical anti-protection while it's loaded. What I have seen happen however, is that Process Explorer reports unprotected processes as protected, likely due to some sort of cache (since the protection doesn't normally change during the lifetime of a process). In those cases restarting Process Explorer worked.

**Comment by roboserg** [comment] 2017-11-06 15:34
Weird, process hacker and process explorer still show "unprotected".

**Comment by Mattiwatti** [comment] 2017-11-06 15:36
Well, yes... that's the intended behaviour as per the README ;) Or do you mean that you expected that stopping PPLKiller reverts process protection? Because if so, no it does not. You will have to reboot if you want the processes to be re-protected.

**Comment by roboserg** [comment] 2017-11-06 15:37
Thanks for the answers? Is rebooting the ONLY way to restore the protection status? This is my last question I swear ;)

**Comment by Mattiwatti** [comment] 2017-11-06 15:43
Yep. There are several reasons why PPLKiller doesn't revert (or even attempt to revert) process protection, but the simplest reason I can think of is by mannger of analogy:

1. You have sex with a hooker in sub-Saharan Africa.
2. You put on a condom afterwards to protect against HIV.

Step 2 is a nice thought in case you are planning to repeat step 1 in the future, but there is some fundamental confusion about what is really being protected in the above scenario. Case in point, protecting an unprotected process isn't the same as having the process protected from the moment it starts. That's why PPLKiller does not and never will "re-protect" processes.

**Comment by roboserg** [comment] 2017-11-06 15:45
Nice analogy :)
So from your words I gather it is possible to revert it in theory, other then reboot. Thanks again.

**Comment by Mattiwatti** [comment] 2017-11-06 15:50
Yes, it's definitely possible. If you take a look at `UnprotectProcesses` in `main.cpp` you'll see there's nothing stopping you from storing, say, an unordered pair of <PID,ProtectionLevel>s and re-applying those in a hypothetical `ReprotectProcesses`, which you can call from `DriverUnload`. There are some things to keep in mind, e.g. processes may no longer exist, but it's really not much more complicated than that.

Will close this now as the original issue seems to be fixed.

**Closed by Mattiwatti** 2017-11-06 15:50 UTC
