### ISSUE TITLE
ERROR 1275

### ISSUE THREAD

**Issue by sirnil** [Mattiwatti/PPLKiller#4] opened 2017-11-07 08:35 UTC
Hello,
I have followed the steps you indicate, and I find a problem.

When I try to start the service, receive an 1275 error. I'm testing on windows 10 x64 1607 build, and also on windows 7 x64, and on both is the same problem.

I'm in test mode.

Can you think of what is due? I have not modified anything, I have only compiled from visual studio 2015

Thanks

**Comment by Mattiwatti** [comment] 2017-11-07 13:13
`sc` statuses are not very helpful to me, I can't control them since they are converted from NTSTATUSes, which are sometimes mine and sometimes not, and even in the case that they are mine, changing an NTSTATUS to a Win32 error is a lossy conversion so I can't say for sure which NTSTATUS this error maps to. Can you follow the instructions in my first comment on bug #2? That should give you more detailed output.

The recommended setup is VS2017 with WDK 10.0.16299.0. That's not to say older versions won't work - as far as I know they should, but I don't test them.

I can already tell you that the driver isn't going to work on Windows 7. That's erm... kind of by design :) Re-read the README if you don't understand. What's odd is that you the same error code on Windows 7 as on Windows 10, which leads me to believe something else is at play. But maybe `sc` is just mapping all kinds of NTSTATUSes to the same error. I can't say.

**Comment by sirnil** [comment] 2017-11-07 14:38
Thanks for the quick reply
you could send me the compiled driver, to test if it really is a compilation error, or is it related to my computer
I have never worked with drivers, and I have had problems installing correctly the VS2017 with WDK :(

**Comment by Mattiwatti** [comment] 2017-11-07 15:29
I wouldn't worry too much about using VS2015 instead of VS2017. VS2015 was the only officially supported version for the WDK until only very recently, and I don't believe anything has changed that would make the driver not work since then. You can assume that if the driver compiles, it should work.

I'm not a big fan of distributing driver binaries; I'd rather people compile the source themselves so they don't have to download a ring 0 binary blob from a potentially unknown/untrusted or compromised source. In theory I could sign them, but it's not worth the hassle since people would still have to enable test signing and add my self-signed root CA to their trusted store. Easier to just compile it.

**Comment by sirnil** [comment] 2017-11-07 18:29
I understand it
probably need more steps than on readme for install driver?

**Comment by Mattiwatti** [comment] 2017-11-07 19:23
The steps in the README should be sufficient for installation, I don't think anything is missing.

What problems are you having? Still the same as in the original post or something else? And did you try enabling logging to get DebugView output?

**Comment by sirnil** [comment] 2017-11-08 09:05
I follow the steps, and when i try to do an 'sc start pplkiller' , the reply is "1275".

if it's really just a problem with the signatures, it's not a problem, since I'm going to buy an EV license. But I do not want to throw away the money, and that it's something different

**Comment by Mattiwatti** [comment] 2017-11-08 16:04
Yes, so the issue is still the same as the original. My reply to this was that you should enable logging so that you can use [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) to find out what is going wrong, since "1275" doesn't mean anything to me.

**Comment by lguilhermee** [comment] 2017-11-10 17:37
`[5272] windows\core\console\open\src\host\srvinit.cpp(480)\ConhostV2.dll!00007FFFA0D017FB: (caller: 00007FFFA0D10628) ReturnHr(52) tid(2bb4) 80070032 Não há suporte para o pedido. `

This is the error priting.

**Comment by gglynn** [comment] 2017-11-13 16:57
I have this problem, as well. Compiled with VS2017 and the latest WDK, testsigning mode is on (the watermark is displayed on the desktop), the WDKTestCert used to sign the driver file is installed in the Trusted Root Certification Authority certificate store, and pplkiller.sys is in the C:\windows\system32\drivers folder.

When I try to start the pplkiller driver with "sc start pplkiller", I get:

[SC] StartService FAILED 1275:

This driver has been blocked from loading

DebugView doesn't show any debug strings during the start attempt, and there's nothing particularly helpful in the Windows Event Log.

The Windows 10 version is 1607 (Anniversary Update) with latest critical and security patches.

**Comment by gglynn** [comment] 2017-11-13 17:19
I figured it out, I targeted the wrong architecture (Win32) when I compiled the driver.  I recompiled it with x64 targeted, and it loads for me, now.

**Comment by Mattiwatti** [comment] 2017-11-13 18:20
OK, good to hear! Will close this then.

**Closed by Mattiwatti** 2017-11-13 18:20 UTC
