### ISSUE TITLE
undefined PROCESS_MITIGATION policies

### ISSUE THREAD

**Issue by FaBeyyy** [Mattiwatti/PPLKiller#9] opened 2018-08-05 12:25 UTC
I am getting

`PROCESS_MITIGATION_SYSTEM_CALL_FILTER_POLICY SystemCallFilterPolicy;
		PROCESS_MITIGATION_PAYLOAD_RESTRICTION_POLICY PayloadRestrictionPolicy;
		PROCESS_MITIGATION_CHILD_PROCESS_POLICY ChildProcessPolicy;`

these structs as undefined. Just wondered if it is safe to comment them out as I got bsod after doing that but I am not sure if that could have anything to do with it.

**Comment by Mattiwatti** [comment] 2018-08-08 03:18
I am guessing that these structs being undefined on your machine is due to having an older version of the WDK installed. Try installing the latest (10.0.17134.0 currently) and also make sure the SDK version is set to the same in the project properties:

![wdkver](https://i.imgur.com/H6dWBI4.png)

However, it **should** have been safe to simply comment them out, as they are not used by PPLKiller and they also do not affect the size of the `PROCESS_MITIGATION_POLICY_INFORMATION` struct if left out.

If you still experience BSODs after upgrading the WDK, I will need some more details on the crash in order to diagnose it:
- Your OS info (major version, bitness and exact kernel version number).
- A crash dump (`.dmp`) file. Make sure you have 'auto reboot on crash' disabled and dump type set to at least kernel memory dump level under advanced system settings. Any BSODs should now produce a `.dmp` file in `%SystemRoot%`. (These can get pretty big but are highly compresssible, I recommend 7zip.)
- The driver file (`.sys`) and debug info (`.pdb`) you compiled. If the BSOD is caused by some kind of project/compiler misconfiguration, I may be able to reproduce the crash without a dump file.

**Comment by Mattiwatti** [comment] 2018-08-26 13:34
Did you manage to resolve this?

**Comment by Mattiwatti** [comment] 2018-08-29 06:37
Damn, it seems this problem was so serious that OP committed suicide over it. I don't see any other explanation for why someone would make a ticket and then not respond to queries afterwards, wasting both their own and my time.

Closed.

**Closed by Mattiwatti** 2018-08-29 06:37 UTC
